name = "cbtmansatas"
main = "src/index.ts"
compatibility_date = "2024-06-01"

[vars]
JWT_SECRET = "9bf165e74c80b8d8d88af0fa6e989056a272032506dfa7fa43ea06b07405c5e8"
CORS_ORIGIN = "https://cbtmansatas.pages.dev"

# Bind ke database PMB EXISTING — JANGAN buat baru!
[[d1_databases]]
binding = "DB"
database_name = "pmb-man1-tasik"
database_id = "b28a3f9e-331d-4bd2-9b85-95b12d6f313f"

# R2 untuk media soal
[[r2_buckets]]
binding = "R2"
bucket_name = "cbt-media"
