'use client';

import { useEffect, useState } from 'react';
import type { CSSProperties } from 'react';
import DOMPurify from 'dompurify';
import katex from 'katex';
import { isFullArabic } from '@/lib/rtl';

const SANITIZE_OPTIONS = {
  USE_PROFILES: { html: true },
  ADD_ATTR: ['data-latex'],
};

const MATH_DELIMITER_RE = /\\\[([\s\S]+?)\\\]|\\\(([\s\S]+?)\\\)|\$\$([\s\S]+?)\$\$|\$([^$\n]+?)\$/g;

type MathSegment =
  | { kind: 'text'; value: string }
  | { kind: 'math'; value: string; displayMode: boolean };

function splitMathText(text: string): MathSegment[] {
  const segments: MathSegment[] = [];
  let lastIndex = 0;
  MATH_DELIMITER_RE.lastIndex = 0;

  for (const match of text.matchAll(MATH_DELIMITER_RE)) {
    const start = match.index ?? 0;
    if (start > lastIndex) segments.push({ kind: 'text', value: text.slice(lastIndex, start) });

    const expression = match[1] ?? match[2] ?? match[3] ?? match[4] ?? '';
    const displayMode = Boolean(match[1] || match[3]);
    if (expression.trim()) {
      segments.push({ kind: 'math', value: expression.trim(), displayMode });
    } else {
      segments.push({ kind: 'text', value: match[0] });
    }
    lastIndex = start + match[0].length;
  }

  if (lastIndex < text.length) segments.push({ kind: 'text', value: text.slice(lastIndex) });
  return segments;
}

export function renderLatexToString(expression: string, displayMode = false): string {
  try {
    return katex.renderToString(expression, {
      displayMode,
      throwOnError: false,
      strict: false,
      trust: false,
    });
  } catch {
    return `<code>${DOMPurify.sanitize(expression)}</code>`;
  }
}

function renderMathNodes(html: string): string {
  const cleanHtml = DOMPurify.sanitize(html, SANITIZE_OPTIONS);
  const container = document.createElement('div');
  container.innerHTML = cleanHtml;

  const walker = document.createTreeWalker(container, NodeFilter.SHOW_TEXT);
  const textNodes: Text[] = [];
  let current: Node | null = walker.nextNode();
  while (current) {
    const parent = current.parentElement;
    // Do not render the HTML generated by KaTeX a second time when editing
    // content that was previously saved by the rich editor.
    if (parent && !parent.closest('.katex, .katex-display, [data-latex]')) {
      textNodes.push(current as Text);
    }
    current = walker.nextNode();
  }

  for (const textNode of textNodes) {
    const text = textNode.nodeValue || '';
    const segments = splitMathText(text);
    if (!segments.some(segment => segment.kind === 'math') || !textNode.parentNode) continue;

    const fragment = document.createDocumentFragment();
    for (const segment of segments) {
      if (segment.kind === 'text') {
        fragment.appendChild(document.createTextNode(segment.value));
        continue;
      }

      const wrapper = document.createElement('span');
      wrapper.className = segment.displayMode ? 'math-block' : 'math-inline';
      wrapper.innerHTML = renderLatexToString(segment.value, segment.displayMode);
      fragment.appendChild(wrapper);
    }
    textNode.parentNode.replaceChild(fragment, textNode);
  }

  return DOMPurify.sanitize(container.innerHTML, SANITIZE_OPTIONS);
}

interface MathContentProps {
  html: string | null | undefined;
  as?: 'div' | 'span';
  className?: string;
  style?: CSSProperties;
}

/**
 * Safely renders stored HTML and LaTeX delimiters:
 * $inline$, \\(inline\\), $$display$$, and \\[display\\].
 */
export default function MathContent({ html, as = 'div', className, style }: MathContentProps) {
  const [renderedHtml, setRenderedHtml] = useState('');
  const [isRtl, setIsRtl] = useState(false);

  useEffect(() => {
    setRenderedHtml(renderMathNodes(html || ''));
    setIsRtl(isFullArabic(html));
  }, [html]);

  const Tag = as;
  return (
    <Tag
      className={isRtl ? `${className || ''} arabic`.trim() : className}
      dir={isRtl ? 'rtl' : undefined}
      style={style}
      suppressHydrationWarning
      dangerouslySetInnerHTML={{ __html: renderedHtml }}
    />
  );
}
